// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbeqtCoYaBSBFL41EhK8XEEaA21bdOLHw',
    appId: '1:352525315000:web:7af496a53d443eabfabd4d',
    messagingSenderId: '352525315000',
    projectId: 'interlink-11d80',
    authDomain: 'interlink-11d80.firebaseapp.com',
    storageBucket: 'interlink-11d80.firebasestorage.app',
    measurementId: 'G-JL6H4V8SS1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE6WJfoOyRzc2BJrj28_IqaJq27pxaII4',
    appId: '1:352525315000:ios:52f61bef26cacf4ffabd4d',
    messagingSenderId: '352525315000',
    projectId: 'interlink-11d80',
    storageBucket: 'interlink-11d80.firebasestorage.app',
    iosBundleId: 'com.example.interlinkmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE6WJfoOyRzc2BJrj28_IqaJq27pxaII4',
    appId: '1:352525315000:ios:52f61bef26cacf4ffabd4d',
    messagingSenderId: '352525315000',
    projectId: 'interlink-11d80',
    storageBucket: 'interlink-11d80.firebasestorage.app',
    iosBundleId: 'com.example.interlinkmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbeqtCoYaBSBFL41EhK8XEEaA21bdOLHw',
    appId: '1:352525315000:web:6b5e7efe59a4c1dcfabd4d',
    messagingSenderId: '352525315000',
    projectId: 'interlink-11d80',
    authDomain: 'interlink-11d80.firebaseapp.com',
    storageBucket: 'interlink-11d80.firebasestorage.app',
    measurementId: 'G-MPSEHVVP2M',
  );
}
